### ISSUE TITLE
About the dataset Daytime-sunny, Night-rainy, Dusk-rainy

### ISSUE THREAD

**Issue by SkeletonOne** [AmingWu/VDD-DAOD#2]
Hi, thanks for your work, I am wondering if you would release the annotations and corresponding image ids of these three datasets? Thx!

**Comment by AmingWu** [comment]
We will release these three datasets this week. Thanks.

**Comment by SkeletonOne** [comment]
@AmingWu Thanks for your effort! Looking forward to it.

**Comment by AmingWu** [comment]
We have released these datasets.

**Comment by SkeletonOne** [comment]
@AmingWu Thanks very much!

**Comment by Fly-dream12** [comment]
Where is daytime-sunny dataset used in this project, do i have to add a new dataset loader? @AmingWu
