### ISSUE TITLE
cannot import name '_C' from 'model'

### ISSUE THREAD

**Issue by seongwn** [AmingWu/VDD-DAOD#4]
Thank you to share your amazing code!

I want to run your training code, but when i run da_train_net_gl.py
I meet follow message: ImportError: cannot import name '_C' from 'model'

I unzip lib/model.zip, lib/roi_da_data_layer.zip lib/roi_data_layer.zip to the project.
And my environment is:
python 3.7 pytorch 1.7.1 cuda 11.2

**Comment by AmingWu** [comment]
Please run      python setup.py develop     in the lib directory.

**Comment by seongwn** [comment]
Thank you! It works!
