### ISSUE TITLE
Trend of domain classification loss?

### ISSUE THREAD

**Issue by wonheee** [AmingWu/VDD-DAOD#6]
Thanks for releasing the code of your interesting research.
I'm experimenting with your method on different datasets in different tasks. 
As a result of the experiment, the domain classification loss in the source domain increases and the domain classification loss in the target domain gradually decreases. (Total domain classification loss decreases.) Could you tell me the correct trend of the domain classification objective function? 
Looking forward to your reply. Thank you.

**Comment by AmingWu** [comment]
In general, the domain classification loss gradually decreases.

**Comment by wonheee** [comment]
Thank you very much!
